export const listFood = [
  {
    id: 100,
    img: "food.png",
    name: "Fried Rice",
    desc: "A stunning Combination Of Contemporary American Fare",
    price: 2560,
  },
  {
    id: 101,
    img: "food.png",
    name: "Meat Ball",
    desc: "A stunning Combination Of Contemporary American Fare",
    price: 3000,
  },
  {
    id: 102,
    img: "food.png",
    name: "Goulash",
    desc: "A stunning Combination Of Contemporary American Fare",
    price: 4000,
  },
  {
    id: 103,
    img: "food.png",
    name: "Fried Banana",
    desc: "A stunning Combination Of Contemporary American Fare",
    price: 2560,
  },
  {
    id: 104,
    img: "food.png",
    name: "Croissant",
    desc: "A stunning Combination Of Contemporary American Fare",
    price: 1203,
  },
  {
    id: 105,
    img: "food.png",
    name: "Waffle",
    desc: "A stunning Combination Of Contemporary American Fare",
    price: 2560,
  },
  {
    id: 106,
    img: "food.png",
    name: "Sakurai",
    desc: "A stunning Combination Of Contemporary American Fare",
    price: 10000,
  },
  {
    id: 107,
    img: "food.png",
    name: "Ramen",
    desc: "A stunning Combination Of Contemporary American Fare",
    price: 10000,
  },
];
