export const listFood = [
  {
    id: 100,
    img: "food.png",
    name: "Goulash",
    desc: "A stunning Combination Of Contemporary American Fare",
    price: `$25.60`,
    qty: 0,
  },
  {
    id: 101,
    img: "food.png",
    name: "Goulash",
    desc: "A stunning Combination Of Contemporary American Fare",
    price: `$25.60`,
    qty: 0,
  },
  {
    id: 102,
    img: "food.png",
    name: "Goulash",
    desc: "A stunning Combination Of Contemporary American Fare",
    price: `$25.60`,
    qty: 0,
  },
  {
    id: 103,
    img: "food.png",
    name: "Goulash",
    desc: "A stunning Combination Of Contemporary American Fare",
    price: `$25.60`,
    qty: 0,
  },
  {
    id: 104,
    img: "food.png",
    name: "Goulash",
    desc: "A stunning Combination Of Contemporary American Fare",
    price: `$25.60`,
    qty: 0,
  },
  {
    id: 105,
    img: "food.png",
    name: "Goulash",
    desc: "A stunning Combination Of Contemporary American Fare",
    price: `$25.60`,
    qty: 0,
  },
  {
    id: 106,
    img: "food.png",
    name: "Goulash",
    desc: "A stunning Combination Of Contemporary American Fare",
    price: `$25.60`,
    qty: 0,
  },
  {
    id: 107,
    img: "food.png",
    name: "Goulash",
    desc: "A stunning Combination Of Contemporary American Fare",
    price: `$25.60`,
    qty: 0,
  },
];
